// <auto-generated />
using LocalBusiness.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBusiness.Migrations
{
    [DbContext(typeof(LocalBusinessContext))]
    [Migration("20211029201514_InitialSeedData")]
    partial class InitialSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LocalBusiness.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Genre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Address = "2137 E Burnside St, Portland, OR 97214",
                            Description = "A family owned mexican restaurant with good burritos. Cash only",
                            Genre = "Mexican",
                            Name = "Ole Ole",
                            Price = 1,
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 2,
                            Address = "3158 E Burnside St, Portland, OR 97214",
                            Description = "The oldest record store in the Pacific Northwest, stocking LP, 45, reel-to-reel, 8-track, cassette, DAT, compact disc, mini-disc, DCC and CD-ROM. ",
                            Genre = "Music",
                            Name = "Millennium Music",
                            Price = 2,
                            Type = "Store"
                        },
                        new
                        {
                            BusinessId = 3,
                            Address = "960 SE 11th Ave, Portland, OR 97214",
                            Description = "Upscale Russian food and house-infused vodkas. ",
                            Genre = "Russian",
                            Name = "Kachka",
                            Price = 4,
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 4,
                            Address = "1109 SE Madison St, Portland, OR 97214",
                            Description = "Family-run cafe serving kebabs, fresh pitas & other Lebanese dishes ",
                            Genre = "Lebanese",
                            Name = "Nicholas",
                            Price = 3,
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 5,
                            Address = "938 E Burnside St, Portland, OR 97214",
                            Description = "A food cart offering made-to-order Thai classics. ",
                            Genre = "Thai",
                            Name = "Thai Champa",
                            Price = 2,
                            Type = "Food Cart"
                        },
                        new
                        {
                            BusinessId = 6,
                            Address = "2250 E Burnside St, Portland, OR 97214",
                            Description = "Cute aesthetic coffee shop with unique coffee flavors, cakes, and pastries",
                            Genre = "Korean",
                            Name = "Soro Soro",
                            Price = 3,
                            Type = "Coffee Shop"
                        },
                        new
                        {
                            BusinessId = 7,
                            Address = "3630 SE Division St, Portland, OR 97202",
                            Description = "Curated vintage housewares, decor, art, clothing & accessories fill this hip, funky boutique.",
                            Genre = "Thrift/Vintage",
                            Name = "Artifact",
                            Price = 2,
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 8,
                            Address = "4035 SE Division St, Portland, OR 97202",
                            Description = "Secondhand store with a bit of everything: clothes, antiques, art, housewares & collectibles.",
                            Genre = "Thrift/Vintage",
                            Name = "Village Merchants",
                            Price = 1,
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 9,
                            Address = "113 SE 28th Ave, Portland, OR 97214",
                            Description = "Fried chicken with Korean or classic Southern flavors",
                            Genre = "Korean",
                            Name = "FOMO Chicken",
                            Price = 2,
                            Type = "Food Cart"
                        },
                        new
                        {
                            BusinessId = 10,
                            Address = "820 SW Washington St, Portland, OR 97205",
                            Description = "Portland's largest independent toy store",
                            Genre = "Toy",
                            Name = "Finnegan's",
                            Price = 3,
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 11,
                            Address = "820 SW Washington St, Portland, OR 97205",
                            Description = "Large table top and card game store with a small video game selection.",
                            Genre = "Game",
                            Name = "Gaurdian Games",
                            Price = 3,
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 12,
                            Address = "1428 SE 36th Ave, Portland, OR 97214",
                            Description = "Small video game/record store specializing in older game systems",
                            Genre = "Game",
                            Name = "Hawthorne Game Exchange",
                            Price = 3,
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 13,
                            Address = "1938 W Burnside St, Portland, OR 97209",
                            Description = "A curated table top game store with a large gaming area and bar",
                            Genre = "Game",
                            Name = "Mox Boarding House",
                            Price = 4,
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 14,
                            Address = "811 NW 23rd Ave, Portland, OR 97210",
                            Description = "A curio shop offering high quality taxidermy, rocks/stones, plants, and general gift items",
                            Genre = "Gifts",
                            Name = "Paxton Gate",
                            Price = 3,
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 15,
                            Address = "2820 NE Sandy Blvd, Portland, OR 97232",
                            Description = "A bright and open tattoo shop offering a variety of",
                            Genre = "Tattoo",
                            Name = "Anatomy Tattoo",
                            Price = 3,
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 16,
                            Address = "2504 SE 50th Ave unit e, Portland, OR 97206",
                            Description = "A curio themed tattoo shop with a small selection of taxidermy for sale in the lobby",
                            Genre = "Tattoo",
                            Name = "Sideshow Alley",
                            Price = 3,
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 17,
                            Address = "1400 SE Stark St, Portland, OR 97214",
                            Description = "Casual restaurant serving out noodles, curries & other classic Thai dishes",
                            Genre = "Thai",
                            Name = "Sunee's Thai",
                            Price = 2,
                            Type = "Restaurant"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
